### ISSUE TITLE
CUDA error: an illegal memory access was encountered caused by new DDP strategy of Pytorch1.9+ 

### ISSUE THREAD

**Issue by wj1tr0y** [ShiqiYu/OpenGait#10]
Thanks for your great contributions to gait recognition community!!
I find this repo cannot run well on pytorch1.9 with CUDA11.1. 
It raises an illegal memory access error when I use default baseline config to train model on CASIA-B.

![image](https://user-images.githubusercontent.com/17830754/138430326-6834adb2-35fc-417e-83aa-3a702bf7e3e9.png)

Sometimes it can run normally at the first serveral steps(but full_loss_num is very small), then error raises.

_After setting **find_unused_parameter** to **True**, the error disappears and training process is back to normal._

it looks like some parameters have been registered but not used in whole model, which triggers this error.

**Comment by zhangzhi-git** [comment]
原来不止我一个人遇到了，这个问题时有时无。但是发生的时候，我解决不了😢

**Comment by noahshen98** [comment]
@zhangzhi-git we recommend you use pytorch 1.6~1.8

**Comment by luwanglin** [comment]
> it looks like some parameters have been registered but not used in whole model, which triggers this error.

我也遇到了，重新加载继续训练也会一直报错这个
