### ISSUE TITLE
Is default.yaml the configuration file for Basegait?

### ISSUE THREAD

**Issue by ZziTaiLeo** [ShiqiYu/OpenGait#101]
![image](https://user-images.githubusercontent.com/42994566/210982884-34fb1edc-36d4-42c8-b165-28fb2d5300b5.png)

**Comment by darkliang** [comment]
No, GaitBase is not public for now. We will public it after accepted.

--------------原始邮件--------------
发件人："Snow ***@***.***&gt;;
发送时间：2023年1月6日(星期五) 晚上6:19
收件人："ShiqiYu/OpenGait" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[ShiqiYu/OpenGait] Is default.yaml the configuration file for Basegait? (Issue #101)
-----------------------------------

**Comment by ZziTaiLeo** [comment]
> No, GaitBase is not public for now. We will public it after accepted.
> […](#)
> --------------原始邮件-------------- 发件人："Snow ***@***.***&gt;; 发送时间：2023年1月6日(星期五) 晚上6:19 收件人："ShiqiYu/OpenGait" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[ShiqiYu/OpenGait] Is default.yaml the configuration file for Basegait? (Issue #101) ----------------------------------- — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Ok，Thanks!
