### ISSUE TITLE
How long did you train on each dataset?

### ISSUE THREAD

**Issue by ZziTaiLeo** [ShiqiYu/OpenGait#102]
Thank you for your great works! 
If it's convenient for you, what are the training times and GPU configurations of all methods.
Looking forward to your reply!

**Comment by ChaoFan996** [comment]
Hi, generally, we need several hours to train [GaitBase](https://arxiv.org/pdf/2211.06597.pdf) on CASIA-B and Gait3D. 
And for OU-MVLP and GREW, we may cost 10-30 hours. (On 8 GPUs, e.g., rtx3090, rtx6000, v100 ...)
Other state-of-the-art methods mostly consume much more time.

**Comment by ZziTaiLeo** [comment]
> 
Thank you for your answer. Also, if I test with my own data, what Segmentation method do you use to obtain the Sil?

**Comment by ChaoFan996** [comment]
In the next few months, we will provide a demo that transforms input video into gait feature vectors covering complete gait recognition workflow in practice, involving pedestrian tracking, segmentation, and recognition processes.
I think this coming demo will help you~

**Comment by ZziTaiLeo** [comment]
All right, thank you!
