### ISSUE TITLE
test baseline on CASIA-B

### ISSUE THREAD

**Issue by zhang123-sys** [ShiqiYu/OpenGait#104]
RuntimeError when running "CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 opengait/main.py --cfgs ./config/baseline/baseline.yaml --phase test"
![image](https://user-images.githubusercontent.com/63956071/215319128-e110dc8e-56a4-456b-968f-8ecb32db03c8.png)

**Comment by zhang123-sys** [comment]
RuntimeError: Error(s) in loading state_dict for Baseline:
        size mismatch for FCs.fc_bin: copying a param with shape torch.Size([31, 512, 256]) from checkpoint, the shape in current model is torch.Size([31, 256, 256]).
        size mismatch for BNNecks.fc_bin: copying a param with shape torch.Size([31, 256, 500]) from checkpoint, the shape in current model is torch.Size([31, 256, 74]).

**Comment by noahshen98** [comment]
make sure that your baseline.yaml has the same setting as：

  SeparateFCs:
    in_channels: 256
    out_channels: 256
    parts_num: 31
  SeparateBNNecks:
    class_num: 74
    in_channels: 256
    parts_num: 31

**Comment by noahshen98** [comment]
you might use the hid pretrained checkpoint, baseline.yaml is for CASIA-B dataset, you need download the right parameters for it.
