### ISSUE TITLE
Does this model supports skeleton based input

### ISSUE THREAD

**Issue by shekarneo** [ShiqiYu/OpenGait#107]
## System information (version)

- Pytorch => :grey_question:
- Operating System / Platform => :grey_question:
- Cuda => :grey_question:

## Detailed description

Hi I wanted to use human pose key-points as inputs, is this possible with retrained models.

## Issue submission checklist
 - [ ] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by noahshen98** [comment]
I recommend you preprocess your keypoints in the format of [seuqnce_number, keypoints_number, keypoints_channel].

Then save it as a pose.pkl for every sequence.

Lastly, add your modified data transform.
