### ISSUE TITLE
pretrained model in HID

### ISSUE THREAD

**Issue by zhang123-sys** [ShiqiYu/OpenGait#111]
What dataset is the pretrained model in HID pretrained?

**Comment by zhang123-sys** [comment]
[pretrained model](https://github.com/ShiqiYu/OpenGait/releases/download/v1.1/pretrained_hid_model.zip)

**Comment by darkliang** [comment]
It was trained with data from the previous HID 2022.

**Comment by zhang123-sys** [comment]
> It was trained with data from the previous HID 2022.

Ok
