### ISSUE TITLE
Where is the gaitbase model and config?

### ISSUE THREAD

**Issue by ZivHong** [ShiqiYu/OpenGait#112]
I can't find the configuration file and pretrained model of Gaitbase, could somebody tell me how to reproduce the Gaitbase result in the paper?

**Comment by darkliang** [comment]
GaitBase is not released for now. We will release it when paper accepted.

**Comment by zhang123-sys** [comment]
OUMVLP.pkl is nearly impossible to generate. When I uncompress the *.tar.gz of OUMVLP, the process will be killed by the server.

**Comment by darkliang** [comment]
> OUMVLP.pkl is nearly impossible to generate. When I uncompress the *.tar.gz of OUMVLP, the process will be killed by the server.

This is unrelated to OpenGait, you should contact the authors of the dataset.
