### ISSUE TITLE
What is the difference between "seqs_batch" and "seqL_batch" ?

### ISSUE THREAD

**Issue by Lune32767** [ShiqiYu/OpenGait#118]
opengait/modeling/base_model.py :
```
def inputs_pretreament(self, inputs):
    seqs_batch, labs_batch, typs_batch, vies_batch, seqL_batch = inputs
```

What is the difference between "seqs_batch" and "seqL_batch" ?

**Comment by ChaoFan996** [comment]
Hi, seqs_batch = [seq1, seq2, ...], and seqL_batch = [len(seq1), len(seq2), ...]
And more, seqL_batch only works when the length of input sequences is unfixed, i.e., len(seq1) != len(seq2).
