### ISSUE TITLE
how to optimize using Adam?

### ISSUE THREAD

**Issue by zhang123-sys** [ShiqiYu/OpenGait#119]
![image](https://user-images.githubusercontent.com/63956071/222960374-5ce0b984-0751-41a1-aa0b-262150bcbae1.png)

**Comment by zhang123-sys** [comment]
betas: (0.9, 0.999)
Error: File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/optim/adam.py", line 66, in __init__
    if not 0.0 <= betas[0] < 1.0:
TypeError: '<=' not supported between instances of 'float' and 'str'

**Comment by darkliang** [comment]
Your config is wrong. Should be 
"""
betas
  - 0.9
  - 0.999
"""

**Comment by zhang123-sys** [comment]
I follow your advice, but error: could not find expected ':'
![image](https://user-images.githubusercontent.com/63956071/223103962-adacb167-1a99-44ac-aeb8-8d0bf5455d85.png)
I add ':', but error: KeyError: 'betas'
![image](https://user-images.githubusercontent.com/63956071/223104411-da5e6673-79a0-478b-b88f-bfff8b9fefb6.png)

**Comment by darkliang** [comment]
Whats your full yaml config? I tried this is ok.
```
optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 5.0e-4
  betas:
    - 0.9
    - 0.999
```

**Comment by zhang123-sys** [comment]
![image](https://user-images.githubusercontent.com/63956071/223117513-8deb4a09-0ae8-4bf1-9363-daca728b503f.png)
I modify baseline_hid.yaml according to you, but Error: KeyError: 'betas'

**Comment by darkliang** [comment]
Everything is normal here, maybe the problem lies in your model code.
