### ISSUE TITLE
About cross_view and single_view

### ISSUE THREAD

**Issue by ZziTaiLeo** [ShiqiYu/OpenGait#121]
Hi, I found there had two way to evaluate, about  cross_view_gallery_evaluation and single_view_gallery_evaluation. I tested the single-view assessment and it matches your repo data. My understanding is that this method only queries all characters in that perspective. I have a question, why not use cross-perspective results?  Is Rank1's accuracy going to increase due to the number of target ids in the gallery?

**Comment by darkliang** [comment]
Hi, the cross view evaluation protocol was proposed by [this work](https://ieeexplore.ieee.org/document/9928336). You can find more details from the paper.
