### ISSUE TITLE
“remove_no_gallery”  but no use.

### ISSUE THREAD

**Issue by ZziTaiLeo** [ShiqiYu/OpenGait#122]
I found that some probes in OUMVLP dataset have no corresponding gallery. Although I found the "remove probe if no gallery" setting in the configuration file, there doesn't seem to be a place to call it in the whole project.

**Comment by noahshen98** [comment]
currently，this setting has not been supported yet， feel free to make a pull request.

**Comment by ZziTaiLeo** [comment]
> currently，this setting has not been supported yet， feel free to make a pull request.

Thanks!
