### ISSUE TITLE
您好，我想在论文中引用你们的“OpenGait: Revisiting Gait Recognition Toward Better Practicality”论文（需要GBT格式），只是谷歌学术上只有预发表的格式

### ISSUE THREAD

**Issue by zhang123-sys** [ShiqiYu/OpenGait#130]
lidargait 的引用
![image](https://user-images.githubusercontent.com/63956071/233770622-0940b0ef-6c0a-4a0c-be24-9c262065977b.png)

谷歌学术上 opengait 的引用
![image](https://user-images.githubusercontent.com/63956071/233771427-16c8b0fc-f70b-4264-a41f-2440dbc7cbd9.png)

**Comment by zhang123-sys** [comment]
你们可以提供GBT格式（CVPR）的“OpenGait: Revisiting Gait Recognition Toward Better Practicality”引用吗？

**Comment by ChaoFan996** [comment]
你好！会议结束后论文正式出版时才有cvpr版本的citation，你可以考虑按以往cvpr文章的格式造一个，我没有用过GBT格式。

**Comment by zhang123-sys** [comment]
好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chao ***@***.***&gt;; 
发送时间: 2023年4月22日(星期六) 下午4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ShiqiYu/OpenGait] 您好，我想在论文中引用你们的“OpenGait: Revisiting Gait Recognition Toward Better Practicality”论文（需要GBT格式），只是谷歌学术上只有预发表的格式 (Issue #130)





 
你好！会议结束后论文正式出版时才有cvpr版本的citation，你可以考虑按以往cvpr文章的格式造一个，我没有用过GBT格式。
