### ISSUE TITLE
Error of testing the CAISA-E dataset with GaitSet. 

### ISSUE THREAD

**Issue by Haijun-Xiong** [ShiqiYu/OpenGait#132]
## ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 2 (pid: 63287) of binary: 
![image](https://user-images.githubusercontent.com/63707850/237000988-38a7295c-696f-44c2-88fa-1d0de49bf12e.png)
when testing the whole test set, I came across the issue above.
But, when only testing the test set of labels (from '1000' to '1014'), it succeeded.
I wonder how I can solve this problem.

**Comment by jdyjjj** [comment]
Try reducing the size of the batch size. Maybe it can work.
