### ISSUE TITLE
More about the result of your GaitBase method on GREW dataset? 

### ISSUE THREAD

**Issue by zhang123-sys** [ShiqiYu/OpenGait#134]
For example, Rank-5 accuracy of GaitBase method on GREW dataset.

**Comment by ChaoFan996** [comment]
You can get the detailed results by testing the model with our provided checkpoints~

**Comment by samly97** [comment]
Assuming you're using the `gaitbase_da_grew.yaml` file, replace the `eval_func` in the config with `evaluate_real_scene`. Then evaluate: e.g., `CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=1 opengait/main.py --cfgs ./configs/gaitbase/gaitbase_da_grew.yaml --phase test`

**Comment by zhang123-sys** [comment]
ok



---Original---
From: "Sam ***@***.***&gt;
Date: Thu, Jun 29, 2023 01:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ShiqiYu/OpenGait] More about the result of your GaitBase methodon GREW dataset?  (Issue #134)




 
Assuming you're using the gaitbase_da_grew.yaml file, replace the eval_func in the config with evaluate_real_scene. Then evaluate: e.g., CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=1 opengait/main.py --cfgs ./configs/gaitbase/gaitbase_da_grew.yaml --phase test

**Comment by chuanfushen** [comment]
noticed that `evaluate_real_scene ` is different from the official evaluation protocol. We make this evaluation mode only for checking accuracy easier. If you would like to get results under the same evaluation protocol as the original publication, you still need to download excel and send the submission to grew website.

**Comment by zhang123-sys** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月15日(星期六) 下午5:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ShiqiYu/OpenGait] More about the result of your GaitBase method on GREW dataset?  (Issue #134)





 
noticed that evaluate_real_scene  is different from the official evaluation protocol. We make this evaluation mode only for checking accuracy easier. If you would like to get results under the same evaluation protocol as the original publication, you still need to download excel and send the submission to grew website.
