### ISSUE TITLE
Date augmentation

### ISSUE THREAD

**Issue by HL-HYX** [ShiqiYu/OpenGait#136]
## Detailed description

Excuse me, how to use data enhancement in the opengait framework, I carefully read the description of data enhancement in the opengait documentation, but it still cannot be applied.

I want use **RandomErasing** data augmentation, but it doesn't work like the following form.

**Comment by HL-HYX** [comment]
![image](https://github.com/ShiqiYu/OpenGait/assets/43193663/7777e562-0033-41ff-be76-bf2880e0c9a3)

**Comment by jdyjjj** [comment]
Please provide more information about the error

**Comment by chuanfushen** [comment]
pls refer to https://github.com/ShiqiYu/OpenGait/blob/master/docs/5.advanced_usages.md#data-augmentation
