### ISSUE TITLE
library version

### ISSUE THREAD

**Issue by Mohades2023** [ShiqiYu/OpenGait#137]
Hi
I am new in this field. can you tell me which version of Python you used?
for the **cython-bbox==0.1.3**  just _python version 3.6_ or lowe can be use(or I could install it) and for **onnx** I need the upper version of python unless using version 1.11.
but for pytorch that you requested for upper than 1.10 its needed newer version of python not 3.6.

could help me with these issues?
thank you

**Comment by ChaoFan996** [comment]
We have no plans to make OpenGait compatible with ONNX.
