### ISSUE TITLE
关于da的概率

### ISSUE THREAD

**Issue by HUAFOR** [ShiqiYu/OpenGait#139]
尊敬的opengait团队：
我注意到您们论文提到使用da的概率是0.5，不过config中多处da的概率设置是0.2，请问概率为0.2的效果会更好是吗~

![image](https://github.com/ShiqiYu/OpenGait/assets/58834906/24e9ab8a-9d95-4181-91c1-f9876155722a)
![image](https://github.com/ShiqiYu/OpenGait/assets/58834906/abd44bf8-c35e-41f8-b98a-65c01c035f25)

**Comment by darkliang** [comment]
(1-0.2)^3=0.512 close to 0.5

--------------原始邮件--------------
发件人："HUAFOR ***@***.***&gt;;
发送时间：2023年7月20日(星期四) 凌晨0:58
收件人："ShiqiYu/OpenGait" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[ShiqiYu/OpenGait] 关于da的概率 (Issue #139)
-----------------------------------

 

 
尊敬的opengait团队：
 我注意到您们论文提到使用da的概率是0.5，不过config中多处da的概率设置是0.2，请问概率为0.2的效果会更好是吗~
