### ISSUE TITLE
The error of collate_fn.py

### ISSUE THREAD

**Issue by Haijun-Xiong** [ShiqiYu/OpenGait#142]
![image](https://github.com/ShiqiYu/OpenGait/assets/63707850/ffb1fb93-2183-42d9-ab35-8f15c47f2228)
When seq_len is less than fs_n, indices are repeated, in np.random.choice(
                         idx_lst, frames_num, replace=False) sorted makes idx_lst orderly, but indices are not orderly. 
It is recommended to change it to the following:
![image](https://github.com/ShiqiYu/OpenGait/assets/63707850/04cada76-bb75-433b-acf8-41a490186dc9)

**Comment by ChaoFan996** [comment]
Directly sorting indices may make the single frame locally repeated, damaging the sequential continuity.
