### ISSUE TITLE
Results of removing illegal sequences on OU-MVLP

### ISSUE THREAD

**Issue by HUAFOR** [ShiqiYu/OpenGait#143]
I would like to know if opengait can provide the results of removing illegal sequences on OU-MVLP as shown in the table below?
If so can you please tell me how I should modify the settings?
![image](https://github.com/ShiqiYu/OpenGait/assets/58834906/5c99be81-1097-4281-984b-2e8992d21b01)

**Comment by ChaoFan996** [comment]
Maybe you can replace this [line](https://github.com/ShiqiYu/OpenGait/blob/962038cc4735cdab14371fa3715f4ea4e792e666/opengait/evaluation/evaluator.py#L97C40-L97C40) with the following code: 
```
if dataset == 'OUMVLP':
    pseq_mask = np.isin(seq_type, probe_seq) & np.isin(
                            view, [probe_view]) & np.isin(label, gallery_y)
else:
    pseq_mask = np.isin(seq_type, probe_seq) & np.isin(
                                        view, [probe_view])
```
