### ISSUE TITLE
My questions of GaitEdge

### ISSUE THREAD

**Issue by WYL-Projects** [ShiqiYu/OpenGait#152]
Dear author,
Thank you for the code base for gait recognition which will come in handy for most of the researchers, much appreciated! However，I have the following questions about the **gaitedge** of Opengait Implementation that I hope to be answered：
1. The CASIA-B* dataset I acquired contains two folders, crop_im and crop_seg, how should this be data processed and adapted to the input of the GaitEdge network?
2. I see that the data processing is to convert a gait sequence to PKL, now there are two folders crop_im and crop_seg, one contains rgb image sequence and the other contains is silhouette maps, how should this be handled? Is it to convert them to pkl format separately?
3. What does the data_in_use parameter in the configs/gaitedge/phase2_gaitedge.yaml configuration file do for the CASIA-B* dataset?
![image](https://github.com/ShiqiYu/OpenGait/assets/50573960/306ef904-baa9-49d3-92a2-1f33ba912958)
4.Looking at the modeling code, the GaitEdge model isn't technically end-to-end, is it? It looks like it needs both silhouette and RGB as inputs. I see that the preprocessing part of the original modeling diagram needs a segmentation, and it looks like the code directly replaces the segment with a silhouette diagram, as shown in Figure 1 below.
![image](https://github.com/ShiqiYu/OpenGait/assets/50573960/ec5da6c7-c4aa-49fd-9be9-fd964dc8259f)

Finally，Lastly, I hope I have given some advice and answers to these questions, thank you very much!

**Comment by darkliang** [comment]
Hi @WYL-Projects , thanks for your interest for our work. For question 1,2 and 3, you need to take a look of https://github.com/ShiqiYu/OpenGait/blob/master/datasets/CASIA-B/README.md#casia-b-1 . For question 4, to some extent,  you are right, it is not end-to-end and need  preprocessed segments.

**Comment by ChaoFan996** [comment]
GaitEdge can directly learn gait features from RGB videos, i.e., in an end-to-end manner. 
Meanwhile, pedestrian segmentation is required to assist the edge generation process and thus can be viewed as a part of preprocessing. 
Totally speaking, these two things should not be conflicting.
