### ISSUE TITLE
Any plan on lite version which on run on jetson nano in realtime?

### ISSUE THREAD

**Issue by scottzhang** [ShiqiYu/OpenGait#156]
## System information (version)

- Pytorch => :grey_question:
- Operating System / Platform => :grey_question:
- Cuda => :grey_question:

## Issue submission checklist
 - [ ] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by scottzhang** [comment]
I have successully run opengait on jetson tx1. But the speed, take more thant 30 seconds to extract the features, is impossible for real use case. We would like a version can identify 15 fps like yolov3-lite run on coco dataset to identify cars,people in realtime.

**Comment by ChaoFan996** [comment]
Hello, thanks for your attentions. 
Up to now, we have no plans to match opengait with edge device. 
Moreover, this code is only used for academic purposes, people cannot use this code for anything that might be considered commercial use.
