### ISSUE TITLE
The checkpoints of GaitBase on Gait3D

### ISSUE THREAD

**Issue by cocoJennie** [ShiqiYu/OpenGait#158]
## Gait3D checkpoints 
The checkpoints of GaitBase in Gait3D datasets seem not right. I have downloaded the released version checkpoint and tested it on the Gait3D. The results are far from the reported one shown in model_zoo.md. Therefore, I trained the model from scratch and the results are very similar to the published one. I think it's better to check whether there is a mistake when you submit the GaitBase checkpoints on the Gait3D dataset.

**Comment by ChaoFan996** [comment]
Thanks for your kind reminder. 
@darkliang, could you check this issue soon? Thanks!

**Comment by darkliang** [comment]
@cocoJennie Hi, the checkpoint is right. You may have used the wrong transform function. Your Gait3D dataset may have cut horizontal pixels, but `BaseSilCuttingTransform` is still used. Please try again with `BaseSilTransform`.

**Comment by cocoJennie** [comment]
@darkliang Thx for your reply! You are right, and I have fixed the transform type for gaitbase_da_gait3d.yaml and got the right results.
