### ISSUE TITLE
Eval func of GREW datasets naming confusion

### ISSUE THREAD

**Issue by enemy1205** [ShiqiYu/OpenGait#164]
In the readme.md of the GREW dataset and in all the parameter configuration files, the recommended test method is "identification_real_scene", and the actual method implemented in the `evaluator.py` file is called "evaluate_real_scene"???
![image](https://github.com/ShiqiYu/OpenGait/assets/30740917/82a0080b-d57a-4a6a-b975-dd136966c397)

![image](https://github.com/ShiqiYu/OpenGait/assets/30740917/47f050ff-c5c4-4d7a-b615-564ac2c01976)

**Comment by darkliang** [comment]
Thanks for your kind reminder, this issue has been fixed in 44fb241.
