### ISSUE TITLE
About GaitLU-1M

### ISSUE THREAD

**Issue by Hpjhpjhs** [ShiqiYu/OpenGait#171]
Thanks for your great work for GaitLU-1M，but I met some issues when I reproduce the GaitSSB. It seems like there might be some issues in the dataset. Could you help me check if it's a problem with my processing or if there are issues inherent to the dataset itself? Thanks again

The error "_pickle.UnpicklingError: invalid load key, '\x00'."

**Comment by ChaoFan996** [comment]
Thanks for your attention. 
I see that your GaitLU-1M may not be uncompressed successfully. 
The dataset is about 300G.
