### ISSUE TITLE
Hello,   what is the reason for converting to a pkl file?

### ISSUE THREAD

**Issue by YingQQ666** [ShiqiYu/OpenGait#189]
## System information (version)

- Pytorch => :grey_question:
- Operating System / Platform => :grey_question:
- Cuda => :grey_question:

## Issue submission checklist
 - [ ] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by ChaoFan996** [comment]
Reading silhouette images frame by frame may take more time.

**Comment by YingQQ666** [comment]
> Reading silhouette images frame by frame may take more time.

Thank you very much
