### ISSUE TITLE
Is it possible to configure OpenGait to operate on a Mac with no Cuda support?

### ISSUE THREAD

**Issue by brettb** [ShiqiYu/OpenGait#190]
- Operating System / Platform => MacOS 14.3
- Cuda => N/A

Is it possible to configure OpenGait to operate on a Mac with no Nvidia/CUDA support? I've attempted to make the configuration modifications to use the CPU with no luck.  I prefer to develop and test on my Mac before pushing to my Nvidia powered servers.

**Comment by ChaoFan996** [comment]
OpenGait requires CUDA and we have not tried such cfgs on Mac, so it may take much work to reach your goal.

**Comment by brettb** [comment]
Okay, I expected that answer after trying to make it work. Thank you for the quick response.
