### ISSUE TITLE
Question about equipment

### ISSUE THREAD

**Issue by linhuaiyi** [ShiqiYu/OpenGait#193]
Question about equipment
Would you mind tell us about what equipment you used when training DeepGaitV2
And how many batch size train at every GPU.
like train layer-22 use batch size 32x4 on A100 80G RAM or something else.

**Comment by ChaoFan996** [comment]
Thanks for your attention.
Typically, we use 4 or 8 RTX 3060 to train gait models.
Moreover, the number of GPUs (with enough memory) should not affect the running of OpenGait if the training command is right.
