### ISSUE TITLE
DeepGait-V2's performance on CCPG

### ISSUE THREAD

**Issue by mollibottie333** [ShiqiYu/OpenGait#198]
I would like to inquire about the silhouette size used in the DeepGaitV2 model. In the CCPG model, the author used silhouette images of size 128x88. Could you please clarify whether DeepGaitV2 uses silhouette sizes of 64x44 or maintains the same size as CCPG, which is 128x88? What about the the silhouette sizes used in the GaitBase and SwinGait?

**Comment by ChaoFan996** [comment]
Thanks for your attention. 
The silhouette size is set to 64x44 in all of our cases.

**Comment by mollibottie333** [comment]
Thank you for your prompt response. I appreciate your assistance. I have a follow-up question regarding the discrepancies I noticed in the results of the CCPG dataset between the two articles.↳

In the first article [https://arxiv.org/pdf/2311.13444.pdf], the rank-1 scores for DeepGaitv2 are reported as 90.3, 96.3, and 91.5 respectively, while in the second article, BigGait's results are listed as 78.6, 84.8, and 80.7. I'm curious about the reasons behind these discrepancies and which set of results should be considered more accurate.
Additionally, I attempted to replicate the results of GAITBASE and DeepGaitv2 on the CCPG dataset using the configuration files provided in the repository. However, I noticed that my results differ from those reported in the paper. Could you confirm if the hyperparameters and experimental settings in the configuration files align with those used in the original experiments described in the articles?
Thank you once again for your assistance. I look forward to your insights on these matters.
