### ISSUE TITLE
这里的   In  x: [n, s, c, h, w] 里面的参数 分别代表步态数据的什么呢？

### ISSUE THREAD

**Issue by HiAleeYang** [ShiqiYu/OpenGait#20]
https://github.com/ShiqiYu/OpenGait/blob/6e71c7ac34603253f688b213d69fb31ae08f3088/lib/modeling/modules.py#L34

**Comment by ChaoFan996** [comment]
hi, [n, s, c, h, w] represents the batch size, sequence dimension, channels, height and width respectively.
