### ISSUE TITLE
GaitGL results on GREW

### ISSUE THREAD

**Issue by GavrielHabib123** [ShiqiYu/OpenGait#215]
Hi,
First of all - thank you for your great work. The repository is amazing and very helpful to further research!
Second, I have noticed that different results for GaitGL on GREW are reported in the [model zoo](https://github.com/ShiqiYu/OpenGait/blob/master/docs/1.model_zoo.md) compared to your [paper](https://arxiv.org/pdf/2303.03301) - 41.5% vs. 47.3%. I used the checkpoint you provided and got 41.2% (more similar to the model zoo result). If the 47.3% is the updated one, I would appreciate if you could please upload its config and the checkpoint itself.

Thanks!
Gavriel

**Comment by SaadShakeel414** [comment]
@GavrielHabib123 Did you use the GREW_Submission as eval_func in the config file. This evaluation generates a CSV file that includes results with a video ID and rank-1 to rank-20 accuracies. Do you know how to read the actual results from this CSV file? I mean which value will be considered as the final rank-1, rank-2,.....,rank-20 accuracy which are reported in papers?
