### ISSUE TITLE
Why batch shuffle affects deepgaitv2 training results

### ISSUE THREAD

**Issue by light201212** [ShiqiYu/OpenGait#217]
Batch_shuffle simply disrupts the order of person IDs, and when calculating triple loss, all embeddings are put together, Shuffle has no effect on the calculation of triple loss. Will softmax be affected? If it doesn't affect why there will be differences in training results. Did I misunderstand somewhere.Thank you for your help.

**Comment by jdyjjj** [comment]
Deepgaitv2 uses 3D convolution to extract temporal features, which is more helpful in extracting temporal features in order than in random order.
