### ISSUE TITLE
Where to find SkeltonGait and SkeltonGait++ pretrained weights on GREW Dataset

### ISSUE THREAD

**Issue by ani0135** [ShiqiYu/OpenGait#218]
I am not able to find SkeltonGait and SkeltonGait++ pretrained weights on GREW Dataset under releases section. May please share.

**Comment by jdyjjj** [comment]
https://huggingface.co/opengait/OpenGait/tree/main/GREW/DeepGaitV2/SkeletonGait
https://huggingface.co/opengait/OpenGait/tree/main/GREW/SkeletonGaitPP/SkeletonGaitPP
​You can find the checkpoints here.



---Original---
From: "Aniket ***@***.***&gt;
Date: Fri, May 31, 2024 16:51 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [ShiqiYu/OpenGait] Where to find SkeltonGait and SkeltonGait++pretrained weights on GREW Dataset (Issue #218)




 
I am not able to find SkeltonGait and SkeltonGait++ pretrained weights on GREW Dataset under releases section. May please share.
