### ISSUE TITLE
SkeltonGait++

### ISSUE THREAD

**Issue by ani0135** [ShiqiYu/OpenGait#220]
Does skeltongait++ requires probe sequence also for heatmap?

**Comment by jdyjjj** [comment]
yes



---Original---
From: "Aniket ***@***.***&gt;
Date: Fri, Jun 7, 2024 09:59 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [ShiqiYu/OpenGait] SkeltonGait++ (Issue #220)




 
Does skeltongait++ requires probe sequence also for heatmap?

**Comment by ani0135** [comment]
But pretreatment_heatmap.py file doesn't make probe folder and its content in heatmap folder due to self.all_ps_data_paths = sorted(glob(os.path.join(pose_root, "*/*/*/*.pkl"))) because it has "*/*/*/*.pkl" . May Please check.

**Comment by jdyjjj** [comment]
Our pretreatment_heatmap.py file preprocesses all data in a dataset, generating a heatmap for all data. The operation of dividing the probe is independent of data generation. Hopefully it can help you.

**Comment by ani0135** [comment]
I am working on GREW dataset and probe is already mentioned in the dataset. My issue is pretreatment_heatmap.py is not generating heatmap specifically for probe folder which was created using pose_2d coordinates.

**Comment by jdyjjj** [comment]
you need to rearrange grew dataset firstly. script under dataset may help you.



---Original---
From: "Aniket ***@***.***&gt;
Date: Fri, Jun 7, 2024 10:53 AM
To: ***@***.***&gt;;
Cc: "Dongyang ***@***.******@***.***&gt;;
Subject: Re: [ShiqiYu/OpenGait] SkeltonGait++ (Issue #220)




 
I am working on GREW dataset and probe is already mentioned in the dataset. My issue is pretreatment_heatmap.py is not generating heatmap specifically for probe folder which was created using pose_2d coordinates.
