### ISSUE TITLE
这个函数的作用是什么呢？

### ISSUE THREAD

**Issue by HiAleeYang** [ShiqiYu/OpenGait#23]
https://github.com/ShiqiYu/OpenGait/blob/49cbc44069878210e11117697be507921db1e3fa/lib/modeling/modules.py#L34
这个函数的最后 return x.view(*_)是不是相当于 return x.view(n, s, c, h ,w)？
如果这么说的话，这个函数没有改变什么?到底发挥了什么作用？没有看懂，望指点

**Comment by HiAleeYang** [comment]
> 

我是在看gaitset代码中https://github.com/ShiqiYu/OpenGait/blob/master/lib/modeling/models/gaitset.py 产生的疑问，这步发挥了什么作用呢
` self.set_block1 = SetBlockWrapper(self.set_block1)`

**Comment by noahshen98** [comment]
您好，SetBlockWrapper作用于不考虑时序维度s的时候，对所有frame做相同操作的时候。

直观的理解上就是，[n, s, c, h, w]---reshape--->  [n*s, c, h, w] ---conv----> [n*s, c, h, w] ---reshape---> [n, s, c, h, w]

**Comment by noahshen98** [comment]
你的理解是对的，唯一要注意的是，输出的c h w 可能跟输入不同。

**Comment by HiAleeYang** [comment]
https://github.com/ShiqiYu/OpenGait/blob/49cbc44069878210e11117697be507921db1e3fa/lib/modeling/models/gaitset.py#L38
这里定义一个` self.set_block1 = SetBlockWrapper(self.set_block1)` 
后面forward里面，有这样， `outs = self.set_block1(sils)`这样调用
https://github.com/ShiqiYu/OpenGait/blob/49cbc44069878210e11117697be507921db1e3fa/lib/modeling/models/gaitset.py#L55
有个疑问是当`outs = self.set_block1(sils)`这样进行forward的时候，对于这个定义的语句（` self.set_block1 = SetBlockWrapper(self.set_block1)` ）来说，**先执行的哪一步？** 是先执行`SetBlockWrapper(self.set_block1)`里面的`self.set_block1`即先将输入的sils进行卷积再调用setBlockwrapper？还是先执行SetBlockWrapper即对输入sils进行维度的改变，在进行卷积？
SetBlockWrapper函数确实改变了输入的维度，但是在改变维度之后，在这个函数中**没有做其他操作（卷积）**，**最后又变回去**？

**Comment by noahshen98** [comment]
先执行SetBlockWrapper即对输入sils进行维度的改变

然后调用self.set_block1的forward

再reshape回5维的tensor

**Comment by noahshen98** [comment]
[n, s, c, h, w]---reshape---> [ns, c, h, w] ---self.set_block1----> [ns, c, h, w] ---reshape---> [n, s, c, h, w]

**Comment by HiAleeYang** [comment]
> 先执行SetBlockWrapper即对输入sils进行维度的改变
> 
> 然后调用self.set_block1的forward
> 
> 再reshape回5维的tensor

感谢，先执行外面的函数，在执行里面的，这个是python语法的哪部分特性呢？

**Comment by noahshen98** [comment]
装饰器
