### ISSUE TITLE
怎么得到CASIA-B*中的align-sils.pkl

### ISSUE THREAD

**Issue by Lxzzzzzzzzzzz** [ShiqiYu/OpenGait#236]
请问CASIA-B*中的align-sils.pkl是怎么得到的，是通过sils.pkl处理得到的吗，具体是哪一个代码呢

**Comment by jdyjjj** [comment]
./datasets/pretreatment.py

**Comment by Lxzzzzzzzzzzz** [comment]
请问是CASIA-B*中的sils.pkl通过./datasets/pretreatment.py处理得到align-sils.pkl的吗？可是sils.pkl的图片shape是128*128，处理之后是64*64而不是align-sils.pkl中的64*44，请问是否还有别的处理？期待早日得到您的回复，非常感谢！！
