### ISSUE TITLE
CCPG上测试skeletongait准确率问题

### ISSUE THREAD

**Issue by YingQQ666** [ShiqiYu/OpenGait#237]
我在CCPG数据集上用skeletongait_CCPG.yaml文件训练得到的模型测试结果为===Rank-1 (Exclude identical-view cases)===
 CL: 50.046,       UP: 59.284,     DN: 62.457,     BG: 67.360，和原始论文上的结果分别差了2.4%，6%，10%
另外在[huggingface](https://huggingface.co/opengait/OpenGait/tree/main/CCPG/DeepGaitV2/SkeletonGait/checkpoints)上下载的checkpoint测试结果只有10%左右
请问是什么原因呢？

**Comment by fffaaaaaa** [comment]
你好，我和你一样，我试了deepgaitv2在gait3d上的效果吗，我的只有60%，论文里写的是74.4%，在huggingface上下载的deepgaitv2-gait3d效果只有52.3%

**Comment by jdyjjj** [comment]
> 我在CCPG数据集上用skeletongait_CCPG.yaml文件训练得到的模型测试结果为===Rank-1 (Exclude identical-view cases)=== CL: 50.046, UP: 59.284, DN: 62.457, BG: 67.360，和原始论文上的结果分别差了2.4%，6%，10% 另外在[huggingface](https://huggingface.co/opengait/OpenGait/tree/main/CCPG/DeepGaitV2/SkeletonGait/checkpoints)上下载的checkpoint测试结果只有10%左右 请问是什么原因呢？
you can use embed2 to get rank-1 result.
