### ISSUE TITLE
请问opengait预处理oumvlp数据集执行rearrange_OUMVLP.py文件  只能处理95%，之后执行pretreatment.py  处理到94%时，抛出以下错误。请问这是哪方面的原因？期待大家的帮助，谢谢！

### ISSUE THREAD

**Issue by rmj2023** [ShiqiYu/OpenGait#238]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\opengait\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "F:\rmj\OpenGait-master\datasets\pretreatment.py", line 39, in imgs2pickle
    if img.sum() <= 10000:
AttributeError: 'NoneType' object has no attribute 'sum'

**Comment by wj1tr0y** [comment]
if img.sum() <= 10000 。有张图可能没读进来，你可以手动加一条判断，看看imread是否成功，不成功可以把这个图过滤掉。或者你print一下这个img的路径，看看是不是有的图片损坏了

**Comment by chuanfushen** [comment]
> 执行rearrange_OUMVLP.py之后的数据集有多大呀，我用3T的移动硬盘装，要装不下了，而且处理的很慢

rearrange_OUMVLP.py是用的软连接，所以应该不会额外有存储占用
