### ISSUE TITLE
这里几个参数代表什么 ipts, labs, seqL ？

### ISSUE THREAD

**Issue by HiAleeYang** [ShiqiYu/OpenGait#24]
https://github.com/ShiqiYu/OpenGait/blob/49cbc44069878210e11117697be507921db1e3fa/lib/modeling/models/gaitset.py#L49
ipts, labs, _, _, seqL = inputs
这个inputs由**哪5部分组成**？其中**ipts, labs, seqL 分别指的什么**？

**Comment by ChaoFan996** [comment]
Hi, the inputs here denote the input silhouettes, labels, views, sequence types and length respectively.
Beside, you may need read more codes to understand them.

**Comment by noahshen98** [comment]
inputs 是由 DataSet + Sampler + CollateFn 三个模块共同协作得到的：
顺序是先由Sampler  sample出indices，然后传递给DataSet->getItems，得到batch = [num_batch, batch_data].
这里的batch_data也就是https://github.com/ShiqiYu/OpenGait/blob/49cbc44069878210e11117697be507921db1e3fa/lib/data/dataset.py#L62
，这里的datalist,跟seq_info。

然后CollateFn对batch = [num_batch, batch_data] 重新处理后得到：
https://github.com/ShiqiYu/OpenGait/blob/49cbc44069878210e11117697be507921db1e3fa/lib/data/collate_fn.py#L97
batch = [fras_batch, labs_batch, typs_batch, vies_batch, SeqL]

也就是你代码里对应的这里：
inputs = [ipts, labs, _, _, seqL]
分别代表输入的frames，标签，着装，视角，序列的长度信息。

**Comment by HiAleeYang** [comment]
Thank you
