### ISSUE TITLE
The dataset download URL of the GREW dataset is invalid.

### ISSUE THREAD

**Issue by wenzhezhai** [ShiqiYu/OpenGait#241]
This is a very impressive piece of work. I wanted to access the GREW dataset website (https://www.grew-benchmark.org/download.html) to apply for the dataset download, but it shows that the domain has expired. Could you please share the link to the GREW dataset? Thank you.

**Comment by jdyjjj** [comment]
I'm not very sure either.  You can ask the [GREW-Benchmark](https://github.com/GREW-Benchmark/GREW-Benchmark) team.
