### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by DrShanUllah** [ShiqiYu/OpenGait#243]
python 3.9.0
Pytorch : 2.1.1+cu118

I was able to run Gaitbase basic code on gait3d using silhouettes.
####################Silhouettes based models are working for me ##############
I am able to run [successful]
model\gait\output\Gait3D\Baseline\GaitBase_DA\checkpoints\GaitBase_DA-60000.pt
This is successful.

############### Skeleton-based models are not working for me ###############
However, I am unable to run any skeleton-based model.

However, I tried to run a skeleton-based algorithm on the same environments.
But I was unsuccessful.

################################ Error 1 ##############################
1)  model\gait\output\GREW\SkeletonGaitPP\SkeletonGaitPP\checkpoints\SkeletonGaitPP-180000.pt
Error: skeletongait++.py", line 74, in inputs_pretreament
    for pose, sil in zip(pose_sils[0], pose_sils[1]):
IndexError: list index out of range

################################ Error 2##############################
2)  \model\gait\output\Gait3D\DeepGaitV2\SkeletonGait\checkpoints\SkeletonGait-60000.pt
Error: torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 2, 3, 3], expected input[138, 1, 64, 44] to have 2 channels, but got 1 channels instead

For vidoe processing, do i need to follow any other step?

**Comment by DrShanUllah** [comment]
It seems I missed processing the skeleton pose, which is why it throws an error requiring two channels. Regarding silhouettes, as paddle-seg is recommended, do we have a recommended repository for HRNet ? Do you have complete code processing for skeleton + silhouette in case we have input video? as current repository assumed that we have already processed silhouettes and already extracted skeletons?

**Comment by jdyjjj** [comment]
> It seems I missed processing the skeleton pose, which is why it throws an error requiring two channels. Regarding silhouettes, as paddle-seg is recommended, do we have a recommended repository for HRNet ? Do you have complete code processing for skeleton + silhouette in case we have input video? as current repository assumed that we have already processed silhouettes and already extracted skeletons?
We assume that there already exist extracted silhouettes and skeletons

**Comment by jdyjjj** [comment]
> It seems I missed processing the skeleton pose, which is why it throws an error requiring two channels. Regarding silhouettes, as paddle-seg is recommended, do we have a recommended repository for HRNet ? Do you have complete code processing for skeleton + silhouette in case we have input video? as current repository assumed that we have already processed silhouettes and already extracted skeletons?

We assume that there already exist extracted silhouettes and skeletons
