### ISSUE TITLE
请问SkeletonGait++可以对casia-b数据集进行检测吗？

### ISSUE THREAD

**Issue by liebaor** [ShiqiYu/OpenGait#245]
## System information (version)

- Pytorch => :grey_question:
- Operating System / Platform => :grey_question:
- Cuda => :grey_question:

## Issue submission checklist
 - [x] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by jdyjjj** [comment]
Sure, but SkeletonGait++ requires the silhouette and pose to be aligned one by one. Casia-b, due to its low resolution, is difficult to extract the corresponding pose. If you can extract the pose and silhouette one by one, it can be run.

**Comment by liebaor** [comment]
> 当然可以，但 SkeletonGait++ 需要将剪影和姿势一一对齐。Casia-b 由于分辨率低，很难提取出相应的姿势。如果可以逐个提取姿势和轮廓，则可以运行它。

非常感谢您的解答！
