### ISSUE TITLE
Some questions about bigGait

### ISSUE THREAD

**Issue by Graysonggg** [ShiqiYu/OpenGait#246]
I benefited a lot from your perfect work.

After reading BigGait, I became interested in the introduction of the common foundation model and would like to ask you a few questions:
1. Have you considered using SAM in the selection of the fundamental model, because of its powerful segmentation ability?
2. In terms of the selection of downstream models, why didn't a stronger baseline, namely Deepgait-v2, be chosen?

Your response would be greatly appreciated.

**Comment by ChaoFan996** [comment]
Thanks for your attention. 
We have tried both DeepGaitV2 and GaitBase and the latter works better for the BigGait framework. 
The causes remain unclear. 
Moreover, we have compared different Large Vision Models for BigGait in Tab. 7 (c for Dinov2, h for SAM).

**Comment by Graysonggg** [comment]
Thanks for patient response.
