### ISSUE TITLE
What do these two lines of code do?

### ISSUE THREAD

**Issue by HiAleeYang** [ShiqiYu/OpenGait#25]
https://github.com/ShiqiYu/OpenGait/blob/49cbc44069878210e11117697be507921db1e3fa/lib/modeling/modules.py#L46

**Comment by HiAleeYang** [comment]
https://github.com/ShiqiYu/OpenGait/blob/49cbc44069878210e11117697be507921db1e3fa/lib/modeling/modules.py#L47

**Comment by ChaoFan996** [comment]
Hi, the first gets the size of `x`(it should follow the form of `[n*s, ...]` in default),  while the second reshape it to `[n, s, ...]` again.

**Comment by HiAleeYang** [comment]
thank you for your reply
