### ISSUE TITLE
关于skeletongait++中pose的尺寸问题

### ISSUE THREAD

**Issue by seakafuka** [ShiqiYu/OpenGait#257]
pretreament处理pose默认是64，处理sil是64or128，为什么在skeletongait++中写了assert pose.size(-1) in [44, 48, 88, 96]；解决方法是注释这一句还是重新制作符合尺寸的数据集呢

**Comment by jdyjjj** [comment]
You can take a look at this [line](https://github.com/ShiqiYu/OpenGait/blob/38616b3c68d633095de3eee8ada8d88c2f449f7c/opengait/data/transform.py#L28) of code.

**Comment by seakafuka** [comment]
好的，我试试
