### ISSUE TITLE
what dose the 'SeqL' mean?

### ISSUE THREAD

**Issue by aleeyang** [ShiqiYu/OpenGait#27]
Hi,
https://github.com/ShiqiYu/OpenGait/blob/49cbc44069878210e11117697be507921db1e3fa/lib/modeling/modules.py#L61
I guess it means the length of the sequence .What is the`seqL[0]` means? By the way, what is the shape of the seqL? What does the each dimension of the seqL correspond to?

**Comment by noahshen98** [comment]
I recommend you print out the seqL, you will feel about it.

**Comment by aleeyang** [comment]
thx, But there is nothing output in the terminal  when I use print such as`print(SeqL)`
There is only training info in the terminal .
I use vscode to run the code in remote server.
Is there a predefined debug method(print the variable) in OpenGait?

**Comment by ChaoFan996** [comment]
Yet, thanks for your suggestions.
At the training phase, the value of `seqL` should be `None` unless the input sequence's length is unfixed.
So, you can set `sample_type` as `unfixed_ordered` and have a try again.
Moreover, at the test phase, the `sample_type` is set to `all_ordered`  in default, 
in another word, you should print out `seqL` at this time to feel it.
(`all` means the unfixed length of real-world gait sequence).

**Comment by aleeyang** [comment]
thank you

**Comment by aleeyang** [comment]
Thank you again your your reply.I compare the original"Gaitset" source code with yours.
The set_pooling is quite different.
The code in the original is https://github.com/AbnerHqC/GaitSet/blob/5535943428b66415530d8379b648b8f74a294219/model/network/gaitset.py#L47
Even the batch_frame euqual to None, it use `        if self.batch_frame is None:
            return torch.max(x, 1)` the max is opeated in the 1 dimension of the x

But your code is just just max,`return self.pooling_func(seqs, **kwargs)` the default dimension is 0
https://github.com/ShiqiYu/OpenGait/blob/6982c35561f5b7b67d43c5e7d2968eb197837f8b/lib/modeling/modules.py#L51

**Comment by aleeyang** [comment]
I mean if the 'SeqL' in your code and 'bacth_frame' in the original code  both point the same subject.When it is None,your code use max in the 0 dim which is the batch_size dimension,it seems wrong....
The original one use max in the 1 dimension(the sequence dimension) whether it is None or not
The set pooling is same as the frame pooling which is used to aggrate the temporal info right?
Maybe my understanding is wrong,hope you can point it out.
Thank you again!

**Comment by ChaoFan996** [comment]
Yet, `**kwargs` can pass the `dim=1` into `self.pooling_func` (you call max here).
