### ISSUE TITLE
what is this line code for ?How

### ISSUE THREAD

**Issue by aleeyang** [ShiqiYu/OpenGait#28]
https://github.com/ShiqiYu/OpenGait/blob/6982c35561f5b7b67d43c5e7d2968eb197837f8b/lib/data/sampler.py#L33

**Comment by aleeyang** [comment]
https://github.com/ShiqiYu/OpenGait/blob/6982c35561f5b7b67d43c5e7d2968eb197837f8b/lib/data/sampler.py#L35
why we need do this ?

**Comment by darkliang** [comment]
[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by darkliang** [comment]
@aleeyang See c3caba81c85f2a845780aef83da2834c5bf81b22.
