### ISSUE TITLE
The  sequence number of obtained features does not match with the number of the testing set when evaluating.

### ISSUE THREAD

**Issue by YunjiePeng** [ShiqiYu/OpenGait#29]
Thanks for your good work.
I'm using the OpenGait as a basic framework for doing my own research. But I met a problem that the sequence number of obtained features does not match with the number of the testing set when evaluating. Any idea?
![image](https://user-images.githubusercontent.com/67147416/147054319-bb085877-8555-4dd2-91ee-b8f701d9c314.png)

**Comment by zhangzhi-git** [comment]
I also encountered the same problem. Is there a solution to the problem please?

**Comment by ChaoFan996** [comment]
If any compress operation (just like pool layer in GaitGL) along the temporal dimension exists, please ensure the batch size equals the number of used GPUs at the testing phase.

**Comment by zhangzhi-git** [comment]
> 

This problem is solved perfectly！3Q  3Q  3Q
