### ISSUE TITLE
Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by scyzero** [ShiqiYu/OpenGait#3]
用笔记本测试的，只有一块显卡所以用的CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 lib/main.py --cfgs ./config/gaitset.yaml --phase train。报错Traceback (most recent call last):
  File "lib/main.py", line 66, in <module>
    run_model(cfgs, training)
  File "lib/main.py", line 49, in run_model
    Model.run_train(model)
  File "/home/yq/OpenGait/lib/modeling/base_model.py", line 371, in run_train
    model.train_step(loss_sum)
  File "/home/yq/OpenGait/lib/modeling/base_model.py", line 307, in train_step
    self.Scaler.scale(loss_sum).backward()
  File "/home/yq/anaconda3/envs/pt14/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/yq/anaconda3/envs/pt14/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
Exception raised from try_all at /pytorch/aten/src/ATen/native/cudnn/Conv.cpp:692 (most recent call first):
请问是怎么回事啊

**Comment by scyzero** [comment]
轮廓分辨率我没有改，使用的默认值

**Comment by noahshen98** [comment]
thanks， can you upload your gaitset.yaml here.

**Comment by scyzero** [comment]
[gaitset.yaml.txt](https://github.com/ShiqiYu/OpenGait/files/7382035/gaitset.yaml.txt)

**Comment by hxi667** [comment]
hi，I also encountered this problem when running “phase1_rec.yaml“ on a CASIA-B* dataset with 4 V100s GPUs, each with 32g of memory. I don't know how to fix it, can you help me?
@noahshen98

**Comment by hxi667** [comment]
This is my configuration file ”phase1_rec.yaml“
[phase1_rec.txt](https://github.com/ShiqiYu/OpenGait/files/11245599/phase1_rec.txt)
