### ISSUE TITLE
The problem about distributed

### ISSUE THREAD

**Issue by w1998w** [ShiqiYu/OpenGait#30]
您的代码使用了分布式训练，我在修改模型时候出现了一下问题：Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing its output (the return value of forward). You can enable unused parameter detection by passing the keyword argument find_unused_parameters=True to torch.nn.parallel.DistributedDataParallel. If you already have this argument set, then the distributed data parallel module wasn’t able to locate the output tensors in the return value of your module’s
forward function. Please include the structure of the return value of forward of your module when reporting this issue (e.g. list,
dict, iterable)
可我确定forward返回值的内容都被用来计算损失了，请问这和分布式训练有关系吗？
您的代码在不改动的情况下可以不使用分布式训练吗

**Comment by w1998w** [comment]
在我修改的部分里面我使用到了nn.Parameter()这个函数不知道会不会影响分布式训练

**Comment by ChaoFan996** [comment]
Hello, I think there may be some parameters you defined have not been used in your model at all.
Beside, the officially recommended [DDP](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) mode is implied in default for OpenGait.
Moreover, the DDP mode is widely used, and there may be no difference between DDP and DP in defining the model for the usual cases.
