### ISSUE TITLE
Can the code run in Windows 11 anaconda environment?

### ISSUE THREAD

**Issue by robot-droid** [ShiqiYu/OpenGait#33]
## System information (version)
- Pytorch = 1.6.0
- Operating System / Platform = Windows 11
- Cuda = 10.1.243

## Detailed description
The problem shows when I run into my computer with the above system information. I create a new conda env and clone this code in the env. But I cannot run the code and the problems are below:
(opengait) C:\Users\Lenovo\OpenGait>set CUDA_VISIBLE_DEVICES=1 & python -m torch.distributed.launch --nproc_per_node=2 lib/main.py --cfgs ./config/baseline.yaml --phase train
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "lib/main.py", line 58, in <module>
  File "lib/main.py", line 58, in <module>
    torch.distributed.init_process_group('nccl', init_method='env://')
    torch.distributed.init_process_group('nccl', init_method='env://')
AttributeError: module 'torch.distributed' has no attribute 'init_process_group'
AttributeError: module 'torch.distributed' has no attribute 'init_process_group'
Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\envs\opengait\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Lenovo\anaconda3\envs\opengait\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lenovo\anaconda3\envs\opengait\lib\site-packages\torch\distributed\launch.py", line 261, in <module>
    main()
  File "C:\Users\Lenovo\anaconda3\envs\opengait\lib\site-packages\torch\distributed\launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['C:\\Users\\Lenovo\\anaconda3\\envs\\opengait\\python.exe', '-u', 'lib/main.py', '--local_rank=1', '--cfgs', './config/baseline.yaml', '--phase', 'train']' returned non-zero exit status 1.

**Comment by darkliang** [comment]
It’s not very supportive for `distributed data parallel` in windows, I suggest you update your torch to higher version, or switch to Linux.

**Comment by robot-droid** [comment]
Ok thanks, I try to look for a computer with Linux. 
May I ask if I really want to run on a Windows computer, what should I change?

**Comment by darkliang** [comment]
You can try the latest version of the torch, and it support DDP on windows for beta feature.

**Comment by robot-droid** [comment]
> You can try the latest version of the torch, and it support DDP on windows for beta feature.

I also cannot run the code

> Did OP solve the problem? I have the same problems on windows 10 Asking for help :)

I also cannot run the code

**Comment by SerJamie** [comment]
Did you try the linux-way? :)

**Comment by jackhanyuan** [comment]
I modified the `lib/main.py`,  it can run on my windows 11 (torch 1.10-cudnn-11.3), you can try it.

https://github.com/jackhanyuan/OpenGait/commit/864b4a2d1291edcf2448069c6fcfee216fc4b08d
