### ISSUE TITLE
Why is the loss multiplied by the world size?

### ISSUE THREAD

**Issue by jasam-sheja** [ShiqiYu/OpenGait#36]
Thank you for making this excellent work open source.
As written in the title, could you please explain the reason behind scaling the loss by the world size?
I didn't find such practice in other distributed training works so far!
Thank you again.

**Comment by ChaoFan996** [comment]
This is indeed a special and confusing operation for pair-based loss (just like triplet loss here) in our DDP practice.
So I draw the following diagram and try to clarify the hidden mechanism.
In the backward process, each GPU should gather the feature embeddings from all the other GPUs first, and then compute the distance of sample pairs within the whole training batch. 
However,  as the green region shows, one crucial detail is that **only the embeddings inside current GPU can backward gradients**!
So in the summarizing stage, which generally means sum up all the GPUs' gradients, the summation is still the 1/n of ideal result. (in another word, the area of n green region is still 1/n that of the blue region, however, we need the total gradients of blue region in fact.)
This is why the pair-based loss should be scaled by n in our implementation.
![img](https://s4.ax1x.com/2022/02/24/bFnjyT.jpg)

**Comment by jasam-sheja** [comment]
Wow, thank you very much for the detailed explanation.
