### ISSUE TITLE
Data Sets

### ISSUE THREAD

**Issue by koiu12** [ShiqiYu/OpenGait#37]
Thank you very much for the code provided. I have a question. How to obtain or preprocess these data sets--"HID2021"、'0001-1000'
gallery_seq_type = {'0001-1000': ['1', '2'],
                        "HID2021": ['0'], '0001-1000-test': ['0']}
    probe_seq_type = {'0001-1000': ['3', '4', '5', '6'],
                      "HID2021": ['1'], '0001-1000-test': ['1']}

**Comment by ChaoFan996** [comment]
"HID" will be supported as soon as possible. (about in next two weeks)

**Comment by ChaoFan996** [comment]
@koiu12 [Hi, HID has been supported now!](https://github.com/ShiqiYu/OpenGait/tree/master/misc/HID)
