### ISSUE TITLE
   raise ArgumentError ctypes.ArgumentError

### ISSUE THREAD

**Issue by HiAleeYang** [ShiqiYu/OpenGait#38]
当我使用Opengait的gaitset 添加自己的网络，并对网络的feature进行了修改
`    final_emb = final_emb.view(n,final_y,-1)#[n,128,_]
        n, s, _, h, w = sils.size()
        retval = {
            'training_feat': {
                'triplet': {'embeddings': final_emb, 'labels': labs}
            },
            'visual_summary': {
                'image/sils': sils.view(n*s, 1, h, w)
            },
            'inference_feat': {
                'embeddings': final_emb
            }
        }`  
但是当我使用DPP训练模型的时候，出现以下错误
File "/project/code/OpenGait/lib/modeling/losses/base.py", line 23, in inner  raise ArgumentError
ctypes.ArgumentError
`
    @functools.wraps(func)
    def inner(*args, **kwds):
        try:
            for k, v in kwds.items():
                kwds[k] = ddp_all_gather(v)

            loss, loss_info = func(*args, **kwds)
            loss *= torch.distributed.get_world_size()
            return loss, loss_info
        except:
            raise ArgumentError
    return inner`
请问是何种原因导致此问题，有何解决办法呢？

**Comment by ChaoFan996** [comment]
Please refer to [here](https://github.com/ShiqiYu/OpenGait/blob/master/docs/2.how_to_create_your_model.md), or check your code with GaitSet carefully.
There may be an error in the return dict object.

**Comment by HiAleeYang** [comment]
thank you, I have solved this problem which is caused by the large dimension of my feature. I downsample the feature and it works well.
But there is a new problem 'CUDA out of memory? In gait recognition, can I reduce the batch size and frames_num_fixed in gaitset.yaml?
https://github.com/ShiqiYu/OpenGait/blob/7c33b33440dfa13141a266309075fc394ff7313e/config/gaitset.yaml#L68

**Comment by ChaoFan996** [comment]
Please refer to [here](https://github.com/ShiqiYu/OpenGait/blob/master/config/default.yaml#L49).
And more, only some relatively latest GPUs support the AMP(auto-mixed precision) mode.
