### ISSUE TITLE
Model fails to test: IndexError: boolean index did not match indexed array along dimension 0;

### ISSUE THREAD

**Issue by woshiljw** [ShiqiYu/OpenGait#4]
hello, we find when we use 2 gpus to test the GaitGL, we will get an error, just like this

CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --master_port 12345 --nproc_per_node=2 lib/main.py --cfgs ./config/gaitgl.yaml --iter 80000 --phase test

we get an error like this
```
File "/OpenGait/lib/utils/evaluation.py", line 67, in identification
gallery_x = feature[gseq_mask, :]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2744 but corresponding boolean dimension is 5485
```
it seems like that the length of the output feature is shorter than the input, and we have checked other test code(gaitset and GLN) which work well when they only test on 2 gpus.

Because we only have two gpus, then how can we test the GaitGL on 2 gpus? Thank you very much!

**Comment by woshiljw** [comment]
Thanks, it can work now. I have another 2 problems 
1. Why we set batch_size bigger than 2 in gaitset can work well on two gpus
2. The performance of GaitGL is worser than that you show, our results are these

[2021-10-20 21:42:00] [INFO]: ===Rank-1 (Exclude identical-view cases)===
[2021-10-20 21:42:00] [INFO]: NM: 97.164,       BG: 94.238,     CL: 83.391

**Comment by noahshen98** [comment]
Hi, the first one is a very good question. Currently, a method like GaitSet is different from GaitGL because seqL is passed in ```self.TP(outs, dim=2, seq_dim=2, seqL=seqL)[0]```. 

We haven't fully supported the case of multiple samples for each GPU for method like GaitGL. But it would be easy to implement. feel free to support this feature and commit your code to help us.

**Comment by woshiljw** [comment]
I know it. Thanks for your help!
