### ISSUE TITLE
关于准确率计算的问题

### ISSUE THREAD

**Issue by SerJamie** [ShiqiYu/OpenGait#40]
想请教一下大佬，这类步态识别模型的准确率（比如在拿CASIA-B进行测试的时候）貌似是根据角度进行的输出，NM,
BG,CL各输出11个角度的准确率，那这些准确率是所有测试样例准确率的平均值吗，我以为的准确率是根据测试样例的数量输出的。（刚刚才开始学习gaitset这篇论文，自己理解得很不到位）

**Comment by noahshen98** [comment]
可以翻阅一下，shiqi yu提出的casiab-b的paper。 里面有详细的准确率解释。

Shiqi Yu, Daoliang Tan and Tieniu Tan, "A Framework for Evaluating the Effect of View Angle, Clothing and Carrying Condition on Gait Recognition," 18th International Conference on Pattern Recognition (ICPR'06), 2006, pp. 441-444, doi: 10.1109/ICPR.2006.67.

**Comment by SerJamie** [comment]
好的谢谢大佬！
