### ISSUE TITLE
the symlink in rearrange_OUMVLP seem to be not work on pretreatment phase

### ISSUE THREAD

**Issue by jackhanyuan** [ShiqiYu/OpenGait#42]
The symlink in rearrange_OUMVLP seem to be not work on pretreatment phase, ERROR for file not found.

**Comment by jackhanyuan** [comment]
The symlink in rearrange_OUMVLP seem to be not work on pretreatment phase 

So I use copy file replace symlink, and use multiprocessing impove speed.

https://github.com/jackhanyuan/OpenGait/blob/master/misc/rearrange_OUMVLP.py

**Comment by noahshen98** [comment]
Hi, I do think that symlink should be better than phyically copy, it saves more space and time.

**Comment by noahshen98** [comment]
After our consideriation, we will accept pull_request form :
https://github.com/ShiqiYu/OpenGait/pull/34/commits/b6feac01e7802c34d01f19a60515c858f18feb10

can you tell us how you meet this issue? have you modified your specific input_path and out_path?
the input_path for rearrange_OUMVLP should be raw from extraction of your downloaded OUMVLP.zip

**Comment by jackhanyuan** [comment]
> Hi, I do think that symlink should be better than phyically copy, it saves more space and time.
Yes, I think so.

> can you tell us how you meet this issue? have you modified your specific input_path and out_path? the input_path for rearrange_OUMVLP should be raw from extraction of your downloaded OUMVLP.zip

I found that the `input_path` and `output_path` in rearrange_OUMVLP should be absolute paths and if they are relative paths, it will cause symlink error. 

Now, I update `rearrange_OUMVLP` again. 

https://github.com/jackhanyuan/OpenGait/blob/master/misc/rearrange_OUMVLP.py

**Comment by noahshen98** [comment]
got it. Thanks for contributing.
