### ISSUE TITLE
The re_ranking algorithm can improve the performance on the HID, but lower for both CASIA-B and OUMVLP?

### ISSUE THREAD

**Issue by jackhanyuan** [ShiqiYu/OpenGait#49]
I found that the `re_ranking` algorithm in [`evaluation.py`](https://github.com/ShiqiYu/OpenGait/blob/master/opengait/utils/evaluation.py) can improve the performance on the HID dataset, but it doesn't work on CASIA-B and OUMVLP, how to explain it ？

**Comment by wj1tr0y** [comment]
Well, I think setting suitable values of `k1,k2` and `lambda_value` is the key.
