### ISSUE TITLE
pychram debug 单步调试

### ISSUE THREAD

**Issue by hxi667** [ShiqiYu/OpenGait#52]
你好，我用win连接远程centos服务器想单步调试代码。不知如何配置pycharm 的Run/Debug configurations  （因为代码使用到了分布式训练，shell 命令多了CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 lib/main.py这些参环境数。）

**Comment by darkliang** [comment]
Hello, we use VScode when we develop OpenGait, so we can't give you any more advice.

**Comment by o0o0o00o0** [comment]
> 你好，我用win连接远程centos服务器想单步调试代码。不知如何配置pycharm 的Run/Debug configurations （因为代码使用到了分布式训练，shell 命令多了CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 lib/main.py这些参环境数。）

write in Environment variables and parameters
