### ISSUE TITLE
关于gaitpart模型训练loss不收敛的问题

### ISSUE THREAD

**Issue by jmx-001** [ShiqiYu/OpenGait#54]
对gaitpart模型进行了8万轮的训练，loss仍然没有收敛的趋势，想请问作者有没有类似情况

**Comment by ChaoFan996** [comment]
Can you provide more details?

**Comment by SerJamie** [comment]
题主是按照gaitpart.yaml的配置进行训练，貌似配置都没有改动，用的单卡训练，训练集是74个，triplet_loss在前1000轮有下降的趋势，是，但目前80000轮的时候上升到0.2100左右

**Comment by darkliang** [comment]
可以提供一下log文件

**Comment by SerJamie** [comment]
貌似日志文件由2.4GB，这边提交不了，我这里有个截图
![gaitpart](https://user-images.githubusercontent.com/55915192/163441681-0ec30604-4cbc-45b7-8276-2cd07d8b7b77.png)

**Comment by SerJamie** [comment]
不过模型的精度确实在不断上升，不知道需不需要再去考虑这个loss不收敛的问题

**Comment by SerJamie** [comment]
这个是我上传到百度网盘的log文件
链接：https://pan.baidu.com/s/1QBHkHnjXNJW38DZagJaE5g?pwd=1234 
提取码：1234

**Comment by ChaoFan996** [comment]
I see. The question maybe you have not understood [this line.](https://github.com/ShiqiYu/OpenGait/blob/fbfc1bb95f2ee06f11d59b46a47ef80b499c2cb4/opengait/modeling/losses/triplet.py#L27)
The loss reducer will exclude all the zero losses.

**Comment by ChaoFan996** [comment]
In another word, here the loss number indicates the convergence status instead of the average loss.

**Comment by SerJamie** [comment]
哦哦原来是这样，非常抱歉我没有完全理解损失函数的计算，谢谢答复！
