### ISSUE TITLE
GREW pretreatment `to_pickle` has size 0

### ISSUE THREAD

**Issue by gosiqueira** [ShiqiYu/OpenGait#57]
## System information (version)
- Pytorch => 1.11
- Operating System / Platform => Ubuntu 20.04
- Cuda => 11.3

## Detailed description
I'm trying to run GREW pretreatment code but it generates no GREW-pkl folder at the end of the process.
I debugged myself and checked if the --dataset flag is set properly and the to_pickle list size before saving the pickle file.
The flag is well set but the size of the list is always 0.

I downloaded the GREW dataset from the link you guys sent me and made de GREW-rearranged folder using the code provided.
I'll keep investigating what is causing such an error and if I find I'll set a fixing PR.

## Issue submission checklist
 - [x] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by ocanevet** [comment]
Hi,

did you solve this issue? I have a similar error in the GREW dataset:

```
  File "datasets/pretreatment.py", line 83, in imgs2pickle
    to_pickle = np.asarray(to_pickle)
ValueError: could not broadcast input array from shape (64,22) into shape (64,)
```
because all the crops are not of the same size:
```
(64, 22)                                                                                                                                                                                                           
(64, 27)       
(64, 25)                                                                                                 
(64, 22)                                                                                                                                                                                                           
(64, 21)
```
whereas on the HID dataset, the output of `np.asarray` yield an array of shape `(59, 128, 128)` for instance.

Thanks for your feedback.

**Comment by noahshen98** [comment]
> Hi,
> 
> 
> 
> did you solve this issue? I have a similar error in the GREW dataset:
> 
> 
> 
> ```
> 
>   File "datasets/pretreatment.py", line 83, in imgs2pickle
> 
>     to_pickle = np.asarray(to_pickle)
> 
> ValueError: could not broadcast input array from shape (64,22) into shape (64,)
> 
> ```
> 
> because all the crops are not of the same size:
> 
> ```
> 
> (64, 22)                                                                                                                                                                                                           
> 
> (64, 27)       
> 
> (64, 25)                                                                                                 
> 
> (64, 22)                                                                                                                                                                                                           
> 
> (64, 21)
> 
> ```
> 
> whereas on the HID dataset, the output of `np.asarray` yield an array of shape `(59, 128, 128)` for instance.
> 
> 
> 
> Thanks for your feedback.

hi, it seems you forget to add flag within the script 

--dataset GREW

**Comment by ocanevet** [comment]
> hi, it seems you forget to add flag within the script
> 
> --dataset GREW

Hi, thanks for your reply. I used the following command:

```
python datasets/pretreatment.py --input_path data/grew-rearranged --output_path data/grew-pkl --dataset GREW
```

and added `print("In grew")` in condition `if dataset == 'GREW':` and got the following output:

```
(64, 24)
(64, 27)
In grew
In grew
datasets/pretreatment.py:84: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  to_pickle = np.asarray(to_pickle)
In grew
[...]
In grew
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "...conda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "datasets/pretreatment.py", line 84, in imgs2pickle
    to_pickle = np.asarray(to_pickle)
ValueError: could not broadcast input array from shape (64,22) into shape (64,)
"""
```

I don't understand why there is the `continue` statement in the `GREW` condition, which skips the `cv2.imresize()` later.

**Comment by ocanevet** [comment]
And using `to_pickle = np.asarray(to_pickle, dtype=object)` as suggested does not work.

**Comment by noahshen98** [comment]
> 

continue should be added since GREW team provides cropped and aligned silhouettes. Therefore, there is not necessary to resize or crop silhouettes further.

**Comment by ocanevet** [comment]
OK thanks. I was processing the optical flow part.
