### ISSUE TITLE
model config and output discussion

### ISSUE THREAD

**Issue by dksath** [ShiqiYu/OpenGait#58]
## System information (version)

- Pytorch => :grey_question:
- Operating System / Platform => :grey_question:
- Cuda => :grey_question:

## Detailed description
Thank you for all the work! I am relatively new to this so sorry for my many questions! I am trying to build an ensemble of all the models, how would i go about configuring the model_cfg? Also which variables would I be needing to extract from the retval dictorionary if I were to perform inference on new data. Thank you in advance!

## Issue submission checklist
 - [x] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by darkliang** [comment]
You can refer to these two documents: 
https://github.com/ShiqiYu/OpenGait/blob/master/docs/1.detailed_config.md
https://github.com/ShiqiYu/OpenGait/blob/master/docs/2.how_to_create_your_model.md
