### ISSUE TITLE
如何使用Baseline-60000.pt进行测试

### ISSUE THREAD

**Issue by w229850** [ShiqiYu/OpenGait#6]
我的运行命令没有反应
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 lib/main.py --cfgs ./config/baseline.yaml --phase train
请问baseline.yaml该怎么配置

**Comment by darkliang** [comment]
First, you should set `--phase=test`. In `baseline.yaml`, only thing you should change is `dataset_root`.

**Comment by w229850** [comment]
明白，感谢大佬！！

**Comment by SerJamie** [comment]
请问题主上述都是在Linux下运行的是吧
