### ISSUE TITLE
How to fix this problem when i want to test

### ISSUE THREAD

**Issue by Flyooofly** [ShiqiYu/OpenGait#60]
## System information (version)

- Pytorch => :grey_question:
- Operating System / Platform => :grey_question:
- Cuda => :grey_question:

## Detailed description
![image](https://user-images.githubusercontent.com/31236750/173245261-0323ce8c-7129-49e4-bd33-4c180aa5e752.png)

## Issue submission checklist
 - [ ] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by darkliang** [comment]
Maybe you can check that the data in your directory`./CASIA-B-pkl` is properly preprocessed.

**Comment by Flyooofly** [comment]
> Maybe you can check that the data in your directory`./CASIA-B-pkl` is properly preprocessed.

Thanks for reply,this is my directory struct,and I make this directiry is fllow this link [https://github.com/ShiqiYu/OpenGait/blob/master/docs/0.prepare_dataset.md](url)
![image](https://user-images.githubusercontent.com/31236750/173318174-31ddfce9-78fa-47e7-8a41-6bd437b54fad.png)

**Comment by darkliang** [comment]
Why only 15 subjects?

**Comment by Flyooofly** [comment]
> The [partition file](https://github.com/ShiqiYu/OpenGait/blob/master/datasets/CASIA-B/CASIA-B_include_005.json) defines which subjects are used for training and which are used for testing. In your case, the subjects used for testing could not be found.

ok, got it, thanks ！
