### ISSUE TITLE
Run OpenGait for real-time recognition through webcam

### ISSUE THREAD

**Issue by andy1213aa** [ShiqiYu/OpenGait#62]
## System information (version)

- Pytorch => 1.10.1
- Operating System / Platform => Ubuntu 22.04
- Cuda => 11.2

## Detailed description
First of all, thank you for arranging so many dataset and models to help those who use it later to save many steps, thank you!
My current work needs to use webcam to capture the gait of pedestrians and identify them in real time through the gait recognition model.
I would like to ask if it is possible to do something like the following in opengait:

**success, frame = video.read()**                                                        _#Read frame from webcam_
**pedestrians_GEI = some_function_calculate_GEI(frames)**           _#calculate the GEI from multiple frames_ 
**encoding = opengait_model(pedestrians_GEI)**                              _#Get the encoding of the specific GEI for later comparison_

That is, can I directly build a recognition model and feed a GEI to get the encoding?
Thank you for reading my question, I hope you understand my point!

## Issue submission checklist
 - [x] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by ChaoFan996** [comment]
This code is only used for academic purposes, people cannot use this code for anything that might be considered commercial use (e.g. build a practical gait recognition system).

**Comment by andy1213aa** [comment]
Understood. Thanks for explanation.
