### ISSUE TITLE
Final_Output_Size vector? Will it be image with embeddings?

### ISSUE THREAD

**Issue by ssaikiran123** [ShiqiYu/OpenGait#66]
## System information (version)

- Pytorch => :grey_question:
- Operating System / Platform => :grey_question:
- Cuda => :grey_question:

## Issue submission checklist
 - [ ] I checked the problem with documentation, FAQ, issues, and have not found solution.
1.Please let me know what is the final output vector size and will it give me the image with embeddings for CASIA B?
2.I went through the paper and know that each frame image is being normalized to 64x44 and 3major process are 1.Local Temporal Aggregation(LTA) 2.Global and Local Feature Extraction(GLFE) 3.Generalize Mean(Gem) Pooling player in Feature Mapping. Final output from the model is Yout from feature mapping which is a vector.
3. I referred this paper [GaitGL(ICCV2021)](https://openaccess.thecvf.com/content/ICCV2021/papers/Lin_Gait_Recognition_via_Effective_Global-Local_Feature_Representation_and_Local_Temporal_ICCV_2021_paper.pdf)

**Comment by ssaikiran123** [comment]
1.Please let me know what is the final output vector size and will it give me the image with embeddings for CASIA B?
2.I went through the paper and know that each frame image is being normalized to 64x44 and 3major process are 1.Local Temporal Aggregation(LTA) 2.Global and Local Feature Extraction(GLFE) 3.Generalize Mean(Gem) Pooling player in Feature Mapping. Final output from the model is Yout from feature mapping which is a vector.

**Comment by darkliang** [comment]
You can check out `tensor.size()` by yourself.

**Comment by noahshen98** [comment]
As you mentioned, you are interested in the shape of the final vectors, you could check the original implement form https://github.com/bb12346/GaitGL/blob/a169610383d58cfc3fa3f5cc7e293860e705e2c1/model/network/vgg_c3d.py#L196

OpenGait wraps the embedding into a python dictionary format, you can print out the tensor as darkliang said. https://github.com/ShiqiYu/OpenGait/blob/8edfc80326166d38e94300ffd143767882fa4025/opengait/modeling/models/baseline.py#L32-L33

**Comment by ssaikiran123** [comment]
OK I will do as suggested and update
