### ISSUE TITLE
I download the pretrained model GaitGL for OUMVLP, and I evaluate the model with my own code. The performance is 89.427, but it is reported as 89.9.

### ISSUE THREAD

**Issue by dashengge** [ShiqiYu/OpenGait#68]
## System information (version)

- Pytorch => :grey_question:
- Operating System / Platform => :grey_question:
- Cuda => :grey_question:

## Issue submission checklist
 - [ ] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by dashengge** [comment]
Is the pytorch version matters?

**Comment by mollibottie333** [comment]
same here, I got a similar result, 89.5. Even though I changed the environment version, the results changed little, can reaching 89.9 as published.
