### ISSUE TITLE
"AttributeError: 'PosixPath' object has no attribute 'startswith'" 

### ISSUE THREAD

**Issue by zhang123-sys** [ShiqiYu/OpenGait#69]
![image](https://user-images.githubusercontent.com/63956071/181764560-cc8ceb4f-f207-42f8-bb37-3b23544f6f6e.png)

**Comment by zhang123-sys** [comment]
subprocess.CalledProcessError: Command '['C:\\Users\\AppData\\Local\\Programs\\Python\\Python37\\python.exe', '-u', 'opengait/main.py', '--local_rank=1', '--cfgs', './config/baseline/baseline.yaml', '--phase', 'train']' returned non-zero exit status 1.

**Comment by noahshen98** [comment]
We highly recommend that users use Linux rather than Windows, since we haven't evaluated our framework on the Windows platform.

**Comment by zhang123-sys** [comment]
> We highly recommend that users use Linux rather than Windows, since we haven't evaluated our framework on the Windows platform.

Ok, I use Linux, but get a similar output.

**Comment by darkliang** [comment]
Do you have two GPU cards or just one?

**Comment by zhang123-sys** [comment]
> on
one

**Comment by darkliang** [comment]
You can try `--nproc_per_node=1`.

**Comment by zhang123-sys** [comment]
> --nproc_per_node=1

Ok, which file to modify?

**Comment by darkliang** [comment]
> > --nproc_per_node=1
> 
> Ok, which file to modify?

The running command.

**Comment by zhang123-sys** [comment]
> > > --nproc_per_node=1
> > 
> > 
> > Ok, which file to modify?
> 
> The running command.

Thank you.

**Comment by zhang123-sys** [comment]
![image](https://user-images.githubusercontent.com/63956071/182085453-51e2a687-f16d-4b05-bbb0-bdfd795474b4.png)

**Comment by zhang123-sys** [comment]
Traceback (most recent call last):
  File "opengait/main.py", line 6, in <module>
    from modeling import models
  File "/hy-nas/OpenGait/opengait/modeling/models/__init__.py", line 8, in <module>
    for (_, module_name, _) in iter_modules([package_dir]):
  File "/usr/lib/python3.8/pkgutil.py", line 129, in iter_modules
    for i in importers:
  File "/usr/lib/python3.8/pkgutil.py", line 419, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1594, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1469, in __init__
  File "<frozen importlib._bootstrap_external>", line 177, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'

**Comment by noahshen98** [comment]
I guess it is related to python version, try to update to python3.9

**Comment by zhang123-sys** [comment]
> I guess it is related to python version, try to update to python3.9

Ok

**Comment by noahshen98** [comment]
@zhang123-sys hi zhang, have you solved this issue?

**Comment by zhang123-sys** [comment]
> @zhang123-sys hi zhang, have you solved this issue?

Not yet.
A new problem "AttributeError: 'PosixPath' object has no attribute 'startswith'", please help me.
![image](https://user-images.githubusercontent.com/63956071/184519371-4b59c7ef-4b2a-44c9-a63e-a4ca4d433b3e.png)

**Comment by noahshen98** [comment]
as I said before, try to upgrade to python39 or downgrade to python36

**Comment by zhang123-sys** [comment]
![image](https://user-images.githubusercontent.com/63956071/189463134-78c6c07e-df88-46c3-a943-8aab518a4e01.png)


> upgrade to python39

upgrade to python39, but problem "AttributeError: 'PosixPath' object has no attribute 'startswith'" exist

**Comment by darkliang** [comment]
Generally, changing the python version can solve this issue, but this issue has nothing to do with OpenGait, so I close it.

**Comment by HUAFOR** [comment]
你好，这个问题我昨天在恒源云训练机器时候遇到过，最后解决，大概率是因为python3.8的问题导致的bug，
在这里我提供我自己的解决方式,希望对你有帮助！：
到目录/lib/python3.8/pkgutli.py下找到：
try:
importer = sys.path_importer_cache[path_item]
在这段话前面添加一行：
path_item = os.fsdecode(path_item)
![image](https://user-images.githubusercontent.com/58834906/219601709-4172cafb-57e6-49b0-b3b0-3b4a0fde4b44.png)

即可解决。
