### ISSUE TITLE
about train&test demo

### ISSUE THREAD

**Issue by frensher** [ShiqiYu/OpenGait#70]
你好,我想问下
train或者test的过程的程序在哪
就是整个piline那种
我没有找到训练的代码   for循环,dataloader,loss,梯度互传那些

**Comment by darkliang** [comment]
You can find the relevant code in the [base model](https://github.com/ShiqiYu/OpenGait/blob/master/opengait/modeling/base_model.py).

**Comment by frensher** [comment]
> You can find the relevant code in the [base model](https://github.com/ShiqiYu/OpenGait/blob/master/opengait/modeling/base_model.py).
3q
