### ISSUE TITLE
about resolution

### ISSUE THREAD

**Issue by frensher** [ShiqiYu/OpenGait#71]
你好,我想问下,哪里控制输入数据的分辨率的128/64?

**Comment by noahshen98** [comment]
Hi, you should use pretreatment.py to pre-process data. With parameter setting of pretreatment.py, you process dataset to pickle data format, and specific resolution(64/or 128).

Then, you should modify transform parameter in model yaml such as gaitset.yaml.

**Comment by noahshen98** [comment]
https://github.com/ShiqiYu/OpenGait/blob/c5e7f6501edeebc3edd0369c511058d1f605d373/configs/default.yaml#L20-L22

https://github.com/ShiqiYu/OpenGait/blob/c5e7f6501edeebc3edd0369c511058d1f605d373/datasets/pretreatment.py#L137

**Comment by frensher** [comment]
> https://github.com/ShiqiYu/OpenGait/blob/c5e7f6501edeebc3edd0369c511058d1f605d373/configs/default.yaml#L20-L22
> 
> https://github.com/ShiqiYu/OpenGait/blob/c5e7f6501edeebc3edd0369c511058d1f605d373/datasets/pretreatment.py#L137

3q
