### ISSUE TITLE
about pretreament

### ISSUE THREAD

**Issue by frensher** [ShiqiYu/OpenGait#79]
你好,我想问下
我注释掉了transform
为什么base_model里的trf_cfgs还是显示我用了变换
![图片](https://user-images.githubusercontent.com/42425485/185840150-8b01c21e-b461-4bfb-90ca-51d054a20819.png)
![图片](https://user-images.githubusercontent.com/42425485/185840241-dbacb650-f833-44c6-8075-f6f664a7e45d.png)
请问,他是有个默认初始的trans吗
即使不设置的话,就调用初始的啊
在哪啊 我没找到

**Comment by noahshen98** [comment]
Yes, default.yaml is used,and you should modify or delete transform parameters inside default.yaml

**Comment by frensher** [comment]
> Yes, default.yaml is used,and you should modify or delete transform parameters inside default.yaml

3q
