### ISSUE TITLE
about ECCV2022-GaitEdge

### ISSUE THREAD

**Issue by frensher** [ShiqiYu/OpenGait#80]
你好
![图片](https://user-images.githubusercontent.com/42425485/186065859-84fbbda1-f096-4bbc-ae54-54d7eacf50e0.png)
我想问下,这个红框这块,不是可以直接生成0,1的mask轮廓图嘛
为什么还要生成浮点数的mask呢

**Comment by darkliang** [comment]
The 0, 1 value itself is obtained by rounding the floating point number, here we are training the segmentation network to make the floating point mask close to the original ground truth.
