### ISSUE TITLE
about dataset input

### ISSUE THREAD

**Issue by frensher** [ShiqiYu/OpenGait#82]
你好
请问有没有考虑过支持其他的数据输入类型
关键点骨架
3d
什么的

**Comment by darkliang** [comment]
Supporting other inputs is not too difficult, but there is currently a lack of suitable models.

**Comment by darkliang** [comment]
For now, SMPL data is supported. You can refer to https://github.com/ShiqiYu/OpenGait/blob/master/configs/smplgait/smplgait.yaml.

**Comment by weilanhanf** [comment]
关键点骨架的属于基于模型的，目前做得不太多
