### ISSUE TITLE
关于OUMVLP的训练集、测试集划分方式有统一的标准吗？

### ISSUE THREAD

**Issue by super-handsome-kang** [ShiqiYu/OpenGait#85]
您好，请问OPMVLP数据集的训练和测试集划分方式是有统一的标准吗？我看您的论文里说的是5153个人的视频用作训练，5154个人用于测试，但是没说是否是前5153个人用于训练，您的opengait好像是奇数号是用于训练，偶数号是用于测试，所以想请教一下应该是按照哪种方式划分才是正确的呢？

**Comment by noahshen98** [comment]
yes, the standard split should follow the segmentation provided by OUMVLP. If you download the raw OUMVLP, it is with a standard split file.

**Comment by super-handsome-kang** [comment]
OK，thank you！
