### ISSUE TITLE
A problem of model GaitEdge when training

### ISSUE THREAD

**Issue by enemy1205** [ShiqiYu/OpenGait#86]
## System information (version)
- Pytorch =>  1.9
- Operating System / Platform =>  Ubuntu 18.04
- Cuda =>  11.3
## Detailed description
In GaitEdge  model file `gaitedge.py` line 52
```
        self.kernel = torch.ones(
            (model_cfg['kernel_size'], model_cfg['kernel_size'])).cuda()
```
However, There is no hyperparameter `kernel_size` in `model_cfg` in `phase2_gaitedge.yaml`

**Comment by darkliang** [comment]
Thanks for your interest in our work, this parameter has been added in f604055.
