### ISSUE TITLE
About Sampler Function

### ISSUE THREAD

**Issue by HiAleeYang** [ShiqiYu/OpenGait#88]
Does OpenGait support any other sampler function in training except the Triplet Sampler?

**Comment by ChaoFan996** [comment]
You can define the sampler [here](https://github.com/ShiqiYu/OpenGait/blob/c2a48191e33ba4da910c2d1afe3b236199590dec/opengait/data/sampler.py) first, and then use it in the [cfg file](https://github.com/ShiqiYu/OpenGait/blob/c2a48191e33ba4da910c2d1afe3b236199590dec/configs/default.yaml#L70).

**Comment by HiAleeYang** [comment]
Thank you very much!
I am not familiar with the DDP.
Could you share some references for writing the code (like the TripletSampler you mentioned above )?

**Comment by ChaoFan996** [comment]
DDP tutorial [here](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html).

**Comment by HiAleeYang** [comment]
appreciate!
