### ISSUE TITLE
The transform in test in train phase

### ISSUE THREAD

**Issue by HiAleeYang** [ShiqiYu/OpenGait#90]
First of all, I use different data augmentation in train and test time.
In the configuration file, there is a `with_test` option, but I find it uses data augmentation for training ,not the test one
Where can I change it ?

The following is about the configuration 

evaluator_cfg:
 ...
  sampler:
    batch_size: 4 #should same to num_gpus
    sample_type: all_ordered
    type: InferenceSampler
  metric: euc # cos
  transform:
    - dataset: CASIA-B
      type: Operation_test

trainer_cfg:
  ...
  transform:
    - dataset: CASIA-B
      type: Operation_train

**Comment by ChaoFan996** [comment]
Refer to [here](https://github.com/ShiqiYu/OpenGait/blob/master/docs/3.detailed_config.md), please.

**Comment by HiAleeYang** [comment]
Thank you
