### ISSUE TITLE
about GaitSet SetPooling Part

### ISSUE THREAD

**Issue by yan811** [ShiqiYu/OpenGait#93]
Hi! It seems that your code did not follow the original GaitSet SP part.
In GaitSet, the author use the mean,median,max function with the attention archeticture.
In your code, you only use the max function.
Why you design in this way?

**Comment by ChaoFan996** [comment]
In GaitSet, 
the authors suggest the max function as the preferential instantiation of the Set Pooling operation.
You can refer to the original paper for more details. (We follow the AAAI-accepted version.)

**Comment by yan811** [comment]
Thanks.
