### ISSUE TITLE
about multiple source of input data

### ISSUE THREAD

**Issue by King-Endeavor** [ShiqiYu/OpenGait#94]
## System information (version)

- Pytorch => :grey_question:
- Operating System / Platform => :grey_question:
- Cuda => :grey_question:

## Detailed description
I get the dataset CASIA-B* and put the CASIA-B* as the input. 
like codes in gaitedge.py 
        ipts, labs, _, _, seqL = inputs
        ratios = ipts[0]
        rgbs = ipts[1]
        sils = ipts[2]
But when I run the code. The error occurs. ips[1] IndexError: list index out of range.
I also add the parameter[data_cfg][data_in_use] in the config.

## Issue submission checklist
 - [ ] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by Bugjudger** [comment]
Add more transform:
https://github.com/ShiqiYu/OpenGait/blob/a71444b967eae8d98b54db26b60eae6a84eac3ad/configs/gaitedge/phase2_gaitedge.yaml#L88-L91
